/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.LinkedList;
import java.util.ArrayList;
import java.util.Random;

public class App {
  final static Random random = new Random();
  final static int maxRandomMonsterNum = 5;
  final static int maxRandomRareNum = 5;
  final static String[] duelPlayer = {"Hisamitsu", "Matsumoto"};

  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    GamePlay duel = new GamePlay(maxRandomMonsterNum, maxRandomRareNum);

    duel.battleStart(duelPlayer[0], duelPlayer[1]);
  }

}
